baseurl = "https://loving-haibt-448d60.netlify.app/"
title = "David Gerard's Website"
author = "David Gerard"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "David Gerard's Website"

[[menu.main]]
    name = "Home"
    url = "/index.html"
    weight = 1
[[menu.main]]
    name = "Code"
    url = "/code/index.html"
    weight = 2
[[menu.main]]
    name = "Papers"
    url = "/papers/index.html"
    weight = 3
[[menu.main]]
    name = "Contact"
    url = "/contact/index.html"
    weight = 4
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/EmpiricalDave"
    weight = 5
